pipelines:
  modi-helper-scripts:
    group: pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      modi-helper-scripts_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/modi-helper-scripts.git
        branch: main
        destination: modi-helper-scripts
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: "{{SECRET:[github][username]}}"
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: modi-helper-scripts
      TEST_DIRECTORY: modi-helper-scripts
      PUSH_DIRECTORY: publish-python-scripts
      PYPI_USERNAME: "{{SECRET:[modi_helper_scripts][username]}}"
      PYPI_PASSWORD: "{{SECRET:[modi_helper_scripts][password]}}"
    template: pypi_package