environments:
  modi_helper_scripts:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[modi_helper_scripts][username]}}"
      PYPI_PASSWORD: "{{SECRET:[modi_helper_scripts][password]}}"
    pipelines:
      - modi-helper-scripts
pipelines:
  modi-helper-scripts:
    group: pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      modi-helper-scripts_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/modi-helper-scripts.git
        branch: main
        destination: modi-helper-scripts
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        branch: main
        destination: publish-python-scripts
    parameters:
      SRC_DIRECTORY: modi-helper-scripts
      BUILD_MAKE_ARGS: install
      TEST_DIRECTORY: modi-helper-scripts
      TEST_MAKE_ARGS: test
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package